- name: Ansible Copy Local to Remote
  hosts: "{{hosts}}"
  vars:
    src_path: "/var/lib/jenkins/workspace/new-app-pipeline/"
    dest_path: "/home/ansadmin"
    config_file_dest_path: "/home"
  tasks:
    # - name: copying files with playbook
    #   become: true
    #   copy:
    #     src: "{{ src_path }}"
    #     dest: "{{ dest_path }}"
    #     owner: ansadmin
    #     group: ansadmin
    #     mode: 0777
    - name: rm git folder and contents
      shell:
        cmd: rm -rf /home/ansadmin/php-docker-full-stack
    - name: git clone
      become: true
      shell:
        cmd: git clone https://github.com/JosephTing91/php-docker-full-stack.git
    - name: edit env path 
      shell: "export PATH=$PATH:/usr/local/bin"
    - name: start containers
      shell:
        cmd: docker-compose up


#try to use execute commands over ssh instead...

#  add this command to edit path variable... export PATH=$PATH:/usr/local/bin


    # - name: pull docker image
    #   become: true
    #   shell:
    #     "docker pull joeting91/nuvalence"